apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: tms-varsel-authority
  namespace: min-side
  labels:
    team: min-side
spec:
  image: {{version}}
  port: 8080
  liveness:
    path: /isalive
    initialDelay: 30
  readiness:
    path: /isready
    initialDelay: 30
  prometheus:
    enabled: true
    path: /metrics
  secureLogs:
    enabled: true
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 50
  leaderElection: true
  resources:
    limits:
      memory: 2400Mi
    requests:
      cpu: "50m"
      memory: 256Mi
  gcp:
    sqlInstances:
      - name: brukervarsler
        type: POSTGRES_14
        tier: db-custom-4-24576
        diskType: SSD
        highAvailability: true
        diskSize: 50
        diskAutoresize: true
        autoBackupHour: 3
        databases:
          - name: brukervarsler
            envVarPrefix: DB
        maintenance:
          day: 1
          hour: 4
        cascadingDelete: false
        flags:
          - name: "cloudsql.enable_pgaudit"
            value: "on"
          - name: "pgaudit.log"
            value: "write,ddl,role"
          - name: "pgaudit.log_parameter"
            value: "on"
  kafka:
    pool: nav-prod
  tokenx:
    enabled: true
  azure:
    application:
      enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: tms-event-api
        - application: tms-varsel-api
        - application: tms-varsel-admin
  env:
    - name: ARCHIVING_THRESHOLD
      value: "365"
    - name: KAFKA_GROUP_ID
      value: "varsel-authority-02"
