name: Bygg og publiser bibliotek for release
on:
  release:
    types:
      - published

permissions:
  packages: write

jobs:
  publish-lib:
    runs-on: ubuntu-latest
    steps:
      - name: Sjekk ut koden
        uses: actions/checkout@v4

      - name: Sett opp java
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'

      - name: Bygg bibliotek
        run:  ./gradlew build -x :app:build

      - name: Publish packages
        run: ./gradlew -Plib_version="$LIB_VERSION" publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LIB_VERSION: ${{ github.event.release.name }}
